1) create a Numpy array

In [ ]:
import numpy as np
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


Access and manipulate elements in the array


In [ ]:
arr1[2]

3

In [ ]:
arr1[2]=5
arr1


array([1, 2, 5])

3) create  a 2-dimensional array and check the shape of the array

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
print("The shape is 2 rows and 3 colums:",arr2.shape)

The shape is 2 rows and 3 colums: (2, 3)


4) Access elements from the 2D array using index positions

In [ ]:
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])

3
3
3
4


5)create an array of type string

In [ ]:
arr3=np.array(['India','china','USA','Mexico'])
print(arr3)

['India' 'china' 'USA' 'Mexico']


In [ ]:
arr3[1]

'china'

6) using the arange() and linspace() fuxn to evenly space values in a specified interval

In [ ]:
arr=np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
arr=np.linspace(0,10,20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


7) create an arary of random values between 0 and 1 in a given shape 

In [ ]:
arr=np.random.rand(10)
print(arr)
print('\n')
arr=np.random.rand(3,4)
print(arr)

[0.38984704 0.58679384 0.12953002 0.00706217 0.78759134 0.65051269
 0.51251797 0.22432359 0.36132487 0.56402846]


[[0.38986898 0.20533229 0.05583827 0.86862142]
 [0.05874295 0.36290789 0.25275464 0.65978827]
 [0.97120792 0.56953077 0.20749746 0.97376812]]


8) craete an array of constant values in a given shape

In [ ]:
print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


9) repeat each element of an array by a specified number of times using repeate() and tile() fuxn

In [ ]:
arr=[0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [ ]:
arr=[0,1,2]
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


10) craete an identity matix using eye() and identity() fuxn

In [ ]:
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


11) create a 5X5 2D array for random numbers between 0 and 1 

In [ ]:
arr=np.random.rand(5,5)
print(arr)

[[0.41684815 0.90619357 0.64746084 0.13511613 0.90499665]
 [0.79664028 0.95321082 0.82047544 0.98211564 0.51957866]
 [0.50742541 0.76410591 0.89709418 0.29167567 0.43410994]
 [0.88753586 0.63107976 0.9957288  0.19886178 0.20457525]
 [0.95202259 0.21972819 0.02327091 0.27501971 0.5480818 ]]


12) sum an array along the column

In [ ]:
print(np.sum(arr,axis=0))

[3.5604723  3.47431825 3.38403018 1.88278894 2.6113423 ]


13)sum an array along the row

In [ ]:
print(np.sum(arr,axis=1))

[3.01061534 4.07202084 2.89441113 2.91778146 2.0181232 ]


14) calculate the mean ,median, standard deviation, variance

In [ ]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

0.5965180788450268
0.6310797613044875
0.3043826349493776
0.09264878845872607


15) sort an array along the row using the sort() fuxn

In [ ]:
arr=np.random.rand(5,5)
print(arr)

[[0.24514248 0.82653021 0.99859219 0.34936786 0.45129959]
 [0.27601676 0.64475927 0.45985676 0.29775781 0.88171723]
 [0.34651362 0.27524439 0.97886459 0.44381048 0.85701729]
 [0.59293872 0.09518829 0.33804662 0.6983722  0.67735289]
 [0.90002859 0.99322282 0.38504963 0.57780827 0.06158492]]


In [ ]:
print(np.sort(arr,axis=1))

[[0.24514248 0.34936786 0.45129959 0.82653021 0.99859219]
 [0.27601676 0.29775781 0.45985676 0.64475927 0.88171723]
 [0.27524439 0.34651362 0.44381048 0.85701729 0.97886459]
 [0.09518829 0.33804662 0.59293872 0.67735289 0.6983722 ]
 [0.06158492 0.38504963 0.57780827 0.90002859 0.99322282]]


16) append elements to an array using the apend() fuxn

In [ ]:
arr=np.array([4,5,6,7])
arr1=np.append(arr,8)
arr1

array([4, 5, 6, 7, 8])

In [ ]:
arr2=np.append(arr,[9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


17) delete multiple elements in an array

In [ ]:
arr2=np.array([4,5,6,7,9,10,11])
print(arr2)
print('\n')
arr5=np.delete(arr2,[1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


18) concatenate elements from 2 arrays

In [ ]:
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])

In [ ]:
cat=np.concatenate((arr1,arr2),axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [ ]:
cat=np.concatenate((arr1,arr2),axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
