In [ ]:
numb = [2, 3, 5, 7, 8]
no = len(numb)
summ = sum(numb)
mean = summ / no
print("The mean or average of all these numbers (", numb, ") is", str(mean))


The mean or average of all these numbers ( [2, 3, 5, 7, 8] ) is 5.0


In [ ]:
numb = [2, 4, 5, 8, 9]
no = len(numb)
numb.sort()
if no % 2 == 0:
    median1 = numb[no//2]
    median2 = numb[no//2 - 1]
    median = (median1 + median2)/2
else:
    median = numb[no//2]
print("The median of the given numbers  (", numb, ") is", str(median))

The median of the given numbers  ( [2, 4, 5, 8, 9] ) is 5


In [ ]:
from collections import Counter
numb = [2, 3, 4, 5, 7, 2]
no = len(numb)
val = Counter(numb)
findMode = dict(val)
mode = [i for i, v in findMode.items() if v == max(list(val.values()))]  
if len(mode) == no:
    findMode = "The group of number do not have any mode"
else:
    findMode = "The mode of a number is / are: " + ', '.join(map(str, mode))
print(findMode)

The mode of a number is / are: 2


In [ ]:
import math
 
def correlationCoefficient(X, Y, n) :
    sum_X = 0
    sum_Y = 0
    sum_XY = 0
    squareSum_X = 0
    squareSum_Y = 0
     
     
    i = 0
    while i < n :
         sum_X = sum_X + X[i]
         sum_Y = sum_Y + Y[i]
         sum_XY = sum_XY + X[i] * Y[i]
         squareSum_X = squareSum_X + X[i] * X[i]
         squareSum_Y = squareSum_Y + Y[i] * Y[i]
         i =  
         corr = (float)(n * sum_XY - sum_X * sum_Y)/
           (float)(math.sqrt((n * squareSum_X -
           sum_X * sum_X)* (n * squareSum_Y -
           sum_Y * sum_Y)))
    return corr

X = [15, 18, 21, 24, 27]
Y = [25, 25, 27, 31, 32]
      

n = len(X)
 print ('{0:.6f}'.format(correlationCoefficient(X, Y, n)))
 

IndentationError: ignored

In [ ]:
 import numpy as np
 import scipy.stats
 x = np.arange(10, 20)
 y = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
 scipy.stats.pearsonr(x, y)   
 scipy.stats.spearmanr(x, y)   
 scipy.stats.kendalltau(x, y) 


SignificanceResult(statistic=0.911111111111111, pvalue=2.9761904761904762e-05)

In [ ]:
import numpy as np

data = np.array([[40, 35, 80],
                 [80, 50, 90],
                 [20, 55, 40],
                 [94, 80, 88],
                 [90, 30, 100]])
print('Input data (N, featuers):', data, data.shape)
N = data.shape[0]
n_dim = data.shape[1]
cov = np.zeros((n_dim, n_dim))

# E(X)
avg = []
for i in range(n_dim):
    avg.append(sum([d[i] for d in data]) / N)
print('avg', avg)

# covariance matrix
for i in range(n_dim):
    for j in range(n_dim):
        var = 0
        for d in data:
            var += (d[i] - avg[i]) * (d[j] - avg[j])
        var /= (N - 1)
        cov[i, j] = var
print('cov', cov)
print('numpy cov', np.cov(data, rowvar=False, bias=False))


Input data (N, featuers): [[ 40  35  80]
 [ 80  50  90]
 [ 20  55  40]
 [ 94  80  88]
 [ 90  30 100]] (5, 3)
avg [64.8, 50.0, 79.6]
cov [[1085.2  130.   670.4]
 [ 130.   387.5  -90. ]
 [ 670.4  -90.   540.8]]
numpy cov [[1085.2  130.   670.4]
 [ 130.   387.5  -90. ]
 [ 670.4  -90.   540.8]]


In [ ]:
import os
import sys

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

X = np.random.rand(50)
Y = 2 * X + np.random.normal(0, 0.1, 50)

np.cov(X, Y)[0, 1]

0.13602799114158948